CREATE TYPE "Role" AS ENUM ('GUEST', 'HOST', 'ADMIN');
CREATE TYPE "AccountStatus" AS ENUM ('PENDING', 'ACTIVE', 'REJECTED');
CREATE TYPE "PropertyType" AS ENUM ('HOMESTAY', 'HOTEL');
CREATE TYPE "PropertyStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE "BookingStatus" AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED');
CREATE TYPE "PaymentStatus" AS ENUM ('SUCCESS', 'FAILED');
CREATE TYPE "PaymentMethod" AS ENUM ('FAKE');
CREATE TABLE "User" ("id" UUID NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "fullName" TEXT NOT NULL, "role" "Role" NOT NULL, "status" "AccountStatus" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Property" ("id" UUID NOT NULL, "hostId" UUID NOT NULL, "type" "PropertyType" NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "district" TEXT NOT NULL, "address" TEXT NOT NULL, "pricePerNight" INTEGER NOT NULL, "depositPercent" INTEGER NOT NULL, "maxGuests" INTEGER NOT NULL, "bedrooms" INTEGER NOT NULL, "beds" INTEGER NOT NULL, "bathrooms" INTEGER NOT NULL, "status" "PropertyStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Property_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PropertyImage" ("id" UUID NOT NULL, "propertyId" UUID NOT NULL, "url" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "PropertyImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Amenity" ("id" UUID NOT NULL, "code" TEXT NOT NULL, "nameVi" TEXT NOT NULL, CONSTRAINT "Amenity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PropertyAmenity" ("propertyId" UUID NOT NULL, "amenityId" UUID NOT NULL, CONSTRAINT "PropertyAmenity_pkey" PRIMARY KEY ("propertyId","amenityId"));
CREATE TABLE "Booking" ("id" UUID NOT NULL, "guestId" UUID NOT NULL, "propertyId" UUID NOT NULL, "checkIn" DATE NOT NULL, "checkOut" DATE NOT NULL, "guestCount" INTEGER NOT NULL, "nightlyPriceSnapshot" INTEGER NOT NULL, "totalNights" INTEGER NOT NULL, "totalAmount" INTEGER NOT NULL, "depositPercentSnapshot" INTEGER NOT NULL, "depositAmount" INTEGER NOT NULL, "remainingAmount" INTEGER NOT NULL, "status" "BookingStatus" NOT NULL DEFAULT 'PENDING_PAYMENT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Booking_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" UUID NOT NULL, "bookingId" UUID NOT NULL, "amount" INTEGER NOT NULL, "status" "PaymentStatus" NOT NULL, "method" "PaymentMethod" NOT NULL DEFAULT 'FAKE', "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE INDEX "User_role_status_idx" ON "User"("role", "status");
CREATE INDEX "Property_hostId_idx" ON "Property"("hostId"); CREATE INDEX "Property_district_idx" ON "Property"("district"); CREATE INDEX "Property_status_pricePerNight_idx" ON "Property"("status", "pricePerNight");
CREATE INDEX "PropertyImage_propertyId_sortOrder_idx" ON "PropertyImage"("propertyId", "sortOrder"); CREATE UNIQUE INDEX "Amenity_code_key" ON "Amenity"("code"); CREATE INDEX "PropertyAmenity_amenityId_idx" ON "PropertyAmenity"("amenityId");
CREATE INDEX "Booking_guestId_createdAt_idx" ON "Booking"("guestId", "createdAt"); CREATE INDEX "Booking_propertyId_checkIn_checkOut_status_idx" ON "Booking"("propertyId", "checkIn", "checkOut", "status"); CREATE INDEX "Payment_bookingId_status_idx" ON "Payment"("bookingId", "status");
ALTER TABLE "Property" ADD CONSTRAINT "Property_hostId_fkey" FOREIGN KEY ("hostId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PropertyImage" ADD CONSTRAINT "PropertyImage_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PropertyAmenity" ADD CONSTRAINT "PropertyAmenity_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PropertyAmenity" ADD CONSTRAINT "PropertyAmenity_amenityId_fkey" FOREIGN KEY ("amenityId") REFERENCES "Amenity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_guestId_fkey" FOREIGN KEY ("guestId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
