import type { AccountStatus, PropertyType, Role } from '@prisma/client';

// Fictional accommodations and account personas. No source listing or seller data.
export const demoAccounts: [string, string, Role, AccountStatus][] = [
  ['admin@stayhub.local', 'Quản trị demo StayHub', 'ADMIN', 'ACTIVE'],
  ['guest@stayhub.local', 'Khách demo StayHub', 'GUEST', 'ACTIVE'],
  ['host@stayhub.local', 'Chủ nhà demo Trung tâm', 'HOST', 'ACTIVE'],
  ['pendinghost@stayhub.local', 'Chủ nhà demo chờ duyệt', 'HOST', 'PENDING'],
  ['host.east@stayhub.local', 'Chủ nhà demo phía Đông', 'HOST', 'ACTIVE'],
  ['host.south@stayhub.local', 'Chủ nhà demo phía Nam', 'HOST', 'ACTIVE'],
];
export const demoAmenities = [
  ['WIFI', 'Wi-Fi'],
  ['AIR_CONDITIONING', 'Máy lạnh'],
  ['PARKING', 'Chỗ đậu xe'],
  ['KITCHEN', 'Bếp'],
  ['SWIMMING_POOL', 'Hồ bơi'],
  ['TV', 'TV'],
  ['WASHING_MACHINE', 'Máy giặt'],
  ['BALCONY', 'Ban công'],
  ['FRIDGE', 'Tủ lạnh'],
  ['ELEVATOR', 'Thang máy'],
  ['GYM', 'Phòng gym'],
  ['WORKSPACE', 'Bàn làm việc'],
  ['HAIR_DRYER', 'Máy sấy tóc'],
  ['HOT_WATER', 'Nước nóng'],
] as const;
export type DemoAmenityCode = (typeof demoAmenities)[number][0];
const layouts = {
  studio: { maxGuests: 2, bedrooms: 0, beds: 1, bathrooms: 1 },
  couple: { maxGuests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
  twin: { maxGuests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
  family: { maxGuests: 4, bedrooms: 2, beds: 2, bathrooms: 2 },
  group: { maxGuests: 6, bedrooms: 3, beds: 3, bathrooms: 2 },
};
const facilities = {
  simple: ['WIFI', 'AIR_CONDITIONING', 'HOT_WATER', 'WORKSPACE'],
  studio: [
    'WIFI',
    'AIR_CONDITIONING',
    'HOT_WATER',
    'KITCHEN',
    'FRIDGE',
    'WORKSPACE',
  ],
  cozy: [
    'WIFI',
    'AIR_CONDITIONING',
    'HOT_WATER',
    'KITCHEN',
    'FRIDGE',
    'BALCONY',
    'WASHING_MACHINE',
  ],
  hotel: [
    'WIFI',
    'AIR_CONDITIONING',
    'HOT_WATER',
    'TV',
    'ELEVATOR',
    'HAIR_DRYER',
    'WORKSPACE',
  ],
  business: [
    'WIFI',
    'AIR_CONDITIONING',
    'HOT_WATER',
    'TV',
    'ELEVATOR',
    'PARKING',
    'FRIDGE',
    'WORKSPACE',
  ],
  family: [
    'WIFI',
    'AIR_CONDITIONING',
    'HOT_WATER',
    'KITCHEN',
    'FRIDGE',
    'WASHING_MACHINE',
    'PARKING',
    'BALCONY',
  ],
  premium: [
    'WIFI',
    'AIR_CONDITIONING',
    'HOT_WATER',
    'TV',
    'KITCHEN',
    'FRIDGE',
    'WASHING_MACHINE',
    'BALCONY',
    'PARKING',
    'SWIMMING_POOL',
    'GYM',
    'ELEVATOR',
  ],
} satisfies Record<string, DemoAmenityCode[]>;
type Spec = [
  number,
  string,
  PropertyType,
  number,
  keyof typeof layouts,
  keyof typeof facilities,
  string,
  string,
  string,
];
type Group = { district: string; hostEmail: string; listings: Spec[] };
const groups: Group[] = [
  {
    district: 'Thủ Đức',
    hostEmail: 'host.east@stayhub.local',
    listings: [
      [
        4,
        'Bến Lá · Căn hộ gia đình',
        'HOMESTAY',
        1450000,
        'family',
        'family',
        'Đặng Văn Bi',
        'Bình Thọ',
        'Căn hộ hai phòng ngủ mang tông gỗ sáng, có ban công, bếp và hai phòng tắm. Máy giặt và chỗ đậu xe phù hợp gia đình bốn người ghé khu vực Bình Thọ.',
      ],
      [
        5,
        'Hiên Vàng Studio',
        'HOMESTAY',
        420000,
        'studio',
        'studio',
        'Hoàng Diệu 2',
        'Linh Chiểu',
        'Studio nhỏ có bàn làm việc cạnh cửa sổ, một giường đôi và bếp mini với tủ lạnh. Không gian mở phù hợp một hoặc hai khách cần nơi nghỉ tiết kiệm tại Linh Chiểu.',
      ],
      [
        6,
        'Trạm Mộc Hotel · Phòng đôi',
        'HOTEL',
        620000,
        'couple',
        'hotel',
        'Võ Văn Ngân',
        'Linh Chiểu',
        'Phòng đôi riêng có góc đọc sách và bàn làm việc, nội thất màu trung tính. Thang máy, TV và phòng tắm với nước nóng phục vụ hai khách công tác tại khu Võ Văn Ngân.',
      ],
      [
        7,
        'Ô Cửa Trúc Homestay',
        'HOMESTAY',
        560000,
        'couple',
        'cozy',
        'Kha Vạn Cân',
        'Linh Trung',
        'Căn nghỉ một phòng ngủ có rèm kem, ban công nhỏ và bếp riêng. Máy giặt phù hợp hai khách lưu trú vài đêm, ưu tiên sinh hoạt chủ động và bữa sáng tự chuẩn bị.',
      ],
      [
        8,
        'Gió Hiệp Bình · Căn hộ rộng',
        'HOMESTAY',
        1750000,
        'group',
        'family',
        'Hiệp Bình',
        'Hiệp Bình Chánh',
        'Căn hộ ba phòng ngủ dành cho nhóm tối đa sáu người, có hai phòng tắm và bàn ăn chung. Bếp, máy giặt và chỗ đậu xe phù hợp gia đình nhiều thế hệ muốn nghỉ cùng nhau.',
      ],
      [
        9,
        'Nếp Sáng Business Hotel',
        'HOTEL',
        880000,
        'twin',
        'business',
        'Phạm Văn Đồng',
        'Hiệp Bình Chánh',
        'Phòng hai giường có góc làm việc cho tối đa ba khách đi công tác. Tòa nhà có thang máy, chỗ đậu xe và tủ lạnh nhỏ; phòng không có bếp.',
      ],
      [
        10,
        'Nhà Bên Tán Cây',
        'HOMESTAY',
        720000,
        'couple',
        'cozy',
        'Tô Ngọc Vân',
        'Linh Đông',
        'Chỗ nghỉ một phòng ngủ có ban công với góc cây xanh trong thiết kế demo. Bếp nhỏ và máy giặt phục vụ hai khách thích đọc sách, nấu ăn và nghỉ ngơi theo nhịp riêng.',
      ],
    ],
  },
  {
    district: 'Quận 1',
    hostEmail: 'host@stayhub.local',
    listings: [
      [
        1,
        'Cam Giấy · Căn hộ ban công',
        'HOMESTAY',
        850000,
        'couple',
        'cozy',
        'Nguyễn Văn Thủ',
        'Đa Kao',
        'Căn hộ một phòng ngủ mang tông cam nhạt, có bàn ăn nhỏ và ban công. Bếp cùng máy giặt phù hợp cặp đôi tự chuẩn bị bữa ăn và khám phá khu vực Đa Kao.',
      ],
      [
        11,
        'Góc Đèn Hotel · Phòng tiêu chuẩn',
        'HOTEL',
        790000,
        'couple',
        'hotel',
        'Lê Thánh Tôn',
        'Bến Nghé',
        'Phòng đôi gọn gàng có bàn làm việc, TV và phòng tắm riêng với nước nóng. Thiết kế phục vụ khách công tác tại trung tâm, ưu tiên nghỉ ngơi thay vì nấu ăn.',
      ],
      [
        12,
        'Ban Mai Cô Giang',
        'HOMESTAY',
        580000,
        'studio',
        'studio',
        'Cô Giang',
        'Cô Giang',
        'Studio mở có một giường đôi, kệ sách thấp và bếp mini. Hai khách có thể làm việc, pha cà phê và tự chuẩn bị bữa sáng trong chuyến ghé trung tâm thành phố.',
      ],
      [
        13,
        'Sắc Kem Boutique Hotel',
        'HOTEL',
        1350000,
        'twin',
        'business',
        'Lý Tự Trọng',
        'Bến Thành',
        'Phòng hai giường với nội thất kem và nâu nhạt cho nhóm ba khách. Thang máy, chỗ đậu xe, tủ lạnh và bàn làm việc đáp ứng lịch hẹn công việc xen kẽ thời gian nghỉ.',
      ],
      [
        14,
        'Nhà Gấp Nắng',
        'HOMESTAY',
        1550000,
        'family',
        'family',
        'Nguyễn Thái Bình',
        'Nguyễn Thái Bình',
        'Căn hộ hai phòng ngủ và hai phòng tắm có bếp riêng, bàn ăn chung và ban công. Thiết kế dành cho gia đình bốn người muốn sinh hoạt cùng nhau khi tham quan khu trung tâm.',
      ],
      [
        15,
        'Tầng Mây Tân Định',
        'HOTEL',
        1080000,
        'couple',
        'business',
        'Trần Quang Khải',
        'Tân Định',
        'Phòng đôi có cửa sổ lớn, bàn làm việc và tủ lạnh nhỏ. Chỗ đậu xe và thang máy thuận tiện cho hai khách công tác; phòng tắm riêng và TV phục vụ thời gian nghỉ.',
      ],
      [
        16,
        'Mùa Nhẹ City Stay',
        'HOMESTAY',
        2100000,
        'family',
        'premium',
        'Nguyễn Hữu Cảnh',
        'Bến Nghé',
        'Căn hộ hai phòng ngủ, hai phòng tắm có ban công, bếp và máy giặt cho gia đình bốn khách. Hồ bơi và phòng gym chung của tòa nhà thuộc thiết kế demo dành cho nhóm thích vận động.',
      ],
    ],
  },
  {
    district: 'Quận 2',
    hostEmail: 'host.east@stayhub.local',
    listings: [
      [
        17,
        'Lá Sông Thảo Điền',
        'HOMESTAY',
        1250000,
        'couple',
        'cozy',
        'Nguyễn Văn Hưởng',
        'Thảo Điền',
        'Căn hộ một phòng ngủ có ban công, góc sofa đọc sách và bếp riêng. Hai khách có thể sinh hoạt theo nhịp chậm ở khu Thảo Điền; máy giặt thuận tiện cho chuyến đi vài ngày.',
      ],
      [
        18,
        'Đồi Cam Hotel',
        'HOTEL',
        950000,
        'twin',
        'business',
        'Quốc Hương',
        'Thảo Điền',
        'Phòng hai giường phục vụ tối đa ba khách với TV, tủ lạnh và bàn làm việc. Tòa nhà có thang máy và chỗ đậu xe, phù hợp nhóm bạn hoặc đồng nghiệp cần phòng riêng.',
      ],
      [
        19,
        'Nếp An Phú Studio',
        'HOMESTAY',
        680000,
        'studio',
        'studio',
        'Lương Định Của',
        'An Phú',
        'Studio có giường đôi và bàn làm việc ngăn bằng kệ thấp, dành cho một hoặc hai khách. Bếp mini và tủ lạnh hỗ trợ những bữa ăn đơn giản trong thời gian ghé An Phú.',
      ],
      [
        20,
        'Khung Trời An Khánh',
        'HOMESTAY',
        1950000,
        'family',
        'premium',
        'Trần Não',
        'An Khánh',
        'Căn hộ hai phòng ngủ có hai phòng tắm, ban công và bàn ăn chung. Bộ tiện ích demo gồm hồ bơi, phòng gym chung và bếp riêng, phù hợp gia đình bốn người cần không gian rộng.',
      ],
      [
        21,
        'Bình An Garden Rooms',
        'HOTEL',
        740000,
        'couple',
        'hotel',
        'Đường số 2',
        'Bình An',
        'Phòng đôi trang trí bằng họa tiết lá, có bàn làm việc và phòng tắm riêng. Thiết kế gọn gàng cho hai khách ghé Bình An; phòng không kèm bếp hoặc hồ bơi.',
      ],
      [
        22,
        'Nhà Một Chiều Gió',
        'HOMESTAY',
        2350000,
        'group',
        'premium',
        'Mai Chí Thọ',
        'An Phú',
        'Căn hộ ba phòng ngủ cho nhóm sáu khách có bếp, máy giặt và hai phòng tắm. Ban công, hồ bơi và phòng gym chung là tiện ích demo dành cho chuyến đi gia đình.',
      ],
    ],
  },
  {
    district: 'Bình Thạnh',
    hostEmail: 'host.south@stayhub.local',
    listings: [
      [
        3,
        'Gỗ Lúa Hotel · Phòng Deluxe',
        'HOTEL',
        1200000,
        'twin',
        'business',
        'Nguyễn Gia Trí',
        'Phường 25',
        'Phòng hai giường với mảng gỗ ấm, bàn làm việc và tủ lạnh nhỏ cho tối đa ba khách. Thang máy và chỗ đậu xe phục vụ nhóm công tác ghé khu Nguyễn Gia Trí.',
      ],
      [
        23,
        'Hiên Cỏ Homestay',
        'HOMESTAY',
        480000,
        'studio',
        'studio',
        'Vũ Tùng',
        'Phường 1',
        'Studio gọn có giường đôi, bàn làm việc và bếp mini đủ cho bữa ăn nhẹ. Hai khách có phòng tắm riêng với nước nóng trong một chỗ nghỉ ưu tiên ngân sách.',
      ],
      [
        24,
        'Mảng Nắng Riverside',
        'HOMESTAY',
        1850000,
        'family',
        'premium',
        'Nguyễn Hữu Cảnh',
        'Phường 22',
        'Căn hộ hai phòng ngủ có ban công và hai phòng tắm cho gia đình bốn khách. Bếp, máy giặt và hồ bơi, phòng gym chung thuộc kịch bản lưu trú cao hơn trong bộ demo.',
      ],
      [
        25,
        'Cửa Sổ Hai Mùa Hotel',
        'HOTEL',
        670000,
        'couple',
        'hotel',
        'Xô Viết Nghệ Tĩnh',
        'Phường 17',
        'Phòng đôi có bàn làm việc cạnh cửa sổ, TV và máy sấy tóc. Thiết kế gọn dành cho hai khách nghỉ ngắn ngày, sử dụng thang máy và phòng tắm riêng thay vì không gian nấu ăn.',
      ],
      [
        26,
        'Bếp Nhỏ Bên Hiên',
        'HOMESTAY',
        920000,
        'couple',
        'cozy',
        'Chu Văn An',
        'Phường 26',
        'Chỗ nghỉ một phòng ngủ có bếp nhỏ, tủ lạnh và ban công với bàn trà. Máy giặt giúp hai khách chủ động trong chuyến đi vài ngày, ưu tiên sinh hoạt riêng tư.',
      ],
      [
        27,
        'Trạm Tre Family Stay',
        'HOMESTAY',
        1450000,
        'family',
        'family',
        'D5',
        'Phường 25',
        'Căn hộ hai phòng ngủ thiết kế cho gia đình bốn người, có bàn ăn chung và hai phòng tắm. Bếp, máy giặt, ban công và chỗ đậu xe phù hợp chuyến đi cùng trẻ nhỏ.',
      ],
    ],
  },
  {
    district: 'Quận 7',
    hostEmail: 'host.south@stayhub.local',
    listings: [
      [
        28,
        'Mây Giấy Tân Phong',
        'HOMESTAY',
        1050000,
        'couple',
        'cozy',
        'Nguyễn Đức Cảnh',
        'Tân Phong',
        'Căn hộ một phòng ngủ có bếp, máy giặt và ban công với bàn nhỏ. Phù hợp cặp đôi muốn không gian riêng khi ghé Tân Phong, tự nấu bữa ăn và nghỉ ngơi sau chuyến đi.',
      ],
      [
        29,
        'Cánh Buồm Business Hotel',
        'HOTEL',
        890000,
        'twin',
        'business',
        'Nguyễn Thị Thập',
        'Tân Quy',
        'Phòng hai giường cho tối đa ba khách có bàn làm việc và tủ lạnh nhỏ. Thang máy, chỗ đậu xe và TV hỗ trợ nhóm công tác tại Tân Quy; phòng không có bếp.',
      ],
      [
        30,
        'Đèn Hiên Phú Mỹ',
        'HOMESTAY',
        650000,
        'studio',
        'studio',
        'Huỳnh Tấn Phát',
        'Phú Mỹ',
        'Studio hai khách có giường đôi, bếp mini và bàn làm việc, trang trí tông gỗ sáng. Không gian nhỏ gọn phù hợp khách ngắn ngày muốn chủ động pha cà phê và chuẩn bị bữa sáng.',
      ],
      [
        31,
        'Nhà Khung Lá',
        'HOMESTAY',
        1650000,
        'family',
        'family',
        'Lâm Văn Bền',
        'Bình Thuận',
        'Căn hộ hai phòng ngủ có hai phòng tắm, bếp và máy giặt cho gia đình bốn người. Ban công và chỗ đậu xe hỗ trợ chuyến đi cùng hành lý; bộ demo không gán hồ bơi cho căn hộ này.',
      ],
      [
        32,
        'Tầng Gió South Stay',
        'HOMESTAY',
        2250000,
        'group',
        'premium',
        'Nguyễn Lương Bằng',
        'Tân Phú',
        'Căn hộ ba phòng ngủ cho tối đa sáu khách có hai phòng tắm và bếp riêng. Ban công, máy giặt, hồ bơi và phòng gym chung thuộc thiết kế demo phù hợp nhóm gia đình.',
      ],
    ],
  },
  {
    district: 'Quận 3',
    hostEmail: 'host@stayhub.local',
    listings: [
      [
        2,
        'Mực Nắng · Studio bên ô cửa',
        'HOMESTAY',
        650000,
        'studio',
        'studio',
        'Võ Văn Tần',
        'Phường 6',
        'Studio mở có giường đôi cạnh ô cửa, bàn làm việc và bếp mini với tủ lạnh. Hai khách có thể đọc sách, tự chuẩn bị bữa ăn nhẹ và nghỉ ngơi trong không gian gọn ở Quận 3.',
      ],
      [
        33,
        'Nốt Trầm Hotel',
        'HOTEL',
        980000,
        'couple',
        'hotel',
        'Nguyễn Đình Chiểu',
        'Phường 5',
        'Phòng đôi mang tông nâu nhạt có TV, góc làm việc và phòng tắm riêng. Thang máy và máy sấy tóc phục vụ hai khách công tác hoặc cặp đôi cần điểm nghỉ đơn giản.',
      ],
      [
        34,
        'Nhà Sách Nhỏ',
        'HOMESTAY',
        1150000,
        'family',
        'family',
        'Trương Định',
        'Phường 6',
        'Căn hộ hai phòng ngủ và hai phòng tắm có kệ sách cùng bàn ăn chung. Bếp, máy giặt và ban công phù hợp gia đình bốn người muốn sinh hoạt riêng trong chuyến khám phá trung tâm.',
      ],
    ],
  },
  {
    district: 'Gò Vấp',
    hostEmail: 'host.south@stayhub.local',
    listings: [
      [
        35,
        'Góc Sân Ban Mai',
        'HOMESTAY',
        350000,
        'couple',
        'simple',
        'Phan Văn Trị',
        'Phường 7',
        'Phòng một giường đôi có bàn làm việc và phòng tắm riêng với nước nóng. Thiết kế tối giản cho hai khách cần chỗ nghỉ tiết kiệm; không kèm bếp hay tiện ích cao cấp.',
      ],
      [
        36,
        'Chồi Xanh Studio',
        'HOMESTAY',
        510000,
        'studio',
        'studio',
        'Nguyễn Oanh',
        'Phường 10',
        'Studio gọn có bàn làm việc, giường đôi và bếp mini cho một hoặc hai khách. Tủ lạnh và nước nóng đáp ứng sinh hoạt cơ bản, phù hợp chuyến đi ngắn ngày ưu tiên ngân sách.',
      ],
    ],
  },
  {
    district: 'Phú Nhuận',
    hostEmail: 'host@stayhub.local',
    listings: [
      [
        37,
        'Đường Mây Hotel',
        'HOTEL',
        760000,
        'couple',
        'hotel',
        'Phan Xích Long',
        'Phường 2',
        'Phòng đôi có bàn làm việc, TV và phòng tắm riêng dành cho hai khách công tác. Thang máy hỗ trợ di chuyển cùng hành lý; mỗi phòng demo là một đơn vị đặt độc lập.',
      ],
      [
        38,
        'Lối Hoa Family Home',
        'HOMESTAY',
        1300000,
        'family',
        'family',
        'Huỳnh Văn Bánh',
        'Phường 12',
        'Căn hộ hai phòng ngủ có hai phòng tắm và bếp chung cho gia đình bốn người. Ban công, máy giặt và chỗ đậu xe phù hợp một chuyến nghỉ vài ngày tại Phú Nhuận.',
      ],
    ],
  },
];
// Reuse the existing curated Unsplash development strategy; no image collection.
const photoSets = {
  studio: [
    'photo-1616486338812-3dadae4b4ace',
    'photo-1600210492486-724fe5c67fb0',
    'photo-1600566753086-00f18fb6b3ea',
  ],
  hotel: [
    'photo-1611892440504-42a792e24d32',
    'photo-1615874959474-d609969a20ed',
    'photo-1600566753086-00f18fb6b3ea',
  ],
  home: [
    'photo-1600607687939-ce8a6c25118c',
    'photo-1600210492486-724fe5c67fb0',
    'photo-1600566753086-00f18fb6b3ea',
  ],
};
export const demoProperties = groups
  .flatMap(({ district, hostEmail, listings }) =>
    listings.map(
      ([
        index,
        name,
        type,
        pricePerNight,
        layout,
        facilitySet,
        street,
        area,
        text,
      ]) => {
        const photos =
          type === 'HOTEL'
            ? photoSets.hotel
            : layout === 'studio'
              ? photoSets.studio
              : photoSets.home;
        return {
          id: `10000000-0000-4000-8000-${String(index).padStart(12, '0')}`,
          hostEmail: index <= 4 ? 'host@stayhub.local' : hostEmail,
          name,
          type,
          district,
          address: `Khu vực đường ${street}, ${area}, ${district}, TP. Hồ Chí Minh (địa chỉ demo)`,
          description: `${text} Nhận phòng từ 14:00, trả phòng trước 12:00; giữ yên tĩnh sau 22:00. Chỗ nghỉ, địa chỉ và giá là dữ liệu tổng hợp cho demo StayHub, không phải cơ sở lưu trú thật.`,
          pricePerNight,
          depositPercent:
            pricePerNight >= 1800000 ? 40 : pricePerNight >= 900000 ? 30 : 20,
          ...layouts[layout],
          status: 'ACTIVE' as const,
          codes: [...facilities[facilitySet]],
          images: photos.map((photo, sortOrder) => ({
            url: `https://images.unsplash.com/${photo}?auto=format&fit=crop&w=1400&q=85`,
            sortOrder,
          })),
        };
      },
    ),
  )
  .sort((a, b) => a.id.localeCompare(b.id));
const legacySeedNames = [
  'Nắng Sài Gòn · Căn hộ ban công',
  'An Nhiên · Studio bên ô cửa',
  'The Mộc Hotel · Phòng Deluxe',
  'Riverside · Góc bình yên',
];

// Exact fingerprints allow a one-time upgrade without overwriting host edits.
export const legacySeedProperties = [
  {
    district: 'Quận 1',
    address: '18 Nguyễn Văn Thủ, Đa Kao, TP. Hồ Chí Minh',
    type: 'HOMESTAY' as const,
    pricePerNight: 850000,
    depositPercent: 30,
    maxGuests: 2,
    photo: 'photo-1600210492486-724fe5c67fb0',
    codes: ['WIFI', 'AIR_CONDITIONING', 'KITCHEN', 'BALCONY'],
  },
  {
    district: 'Quận 3',
    address: '42 Võ Văn Tần, TP. Hồ Chí Minh',
    type: 'HOMESTAY' as const,
    pricePerNight: 650000,
    depositPercent: 20,
    maxGuests: 2,
    photo: 'photo-1616486338812-3dadae4b4ace',
    codes: ['WIFI', 'AIR_CONDITIONING', 'KITCHEN', 'WASHING_MACHINE'],
  },
  {
    district: 'Bình Thạnh',
    address: '65 Nguyễn Gia Trí, TP. Hồ Chí Minh',
    type: 'HOTEL' as const,
    pricePerNight: 1200000,
    depositPercent: 40,
    maxGuests: 3,
    photo: 'photo-1611892440504-42a792e24d32',
    codes: ['WIFI', 'AIR_CONDITIONING', 'PARKING', 'TV'],
  },
  {
    district: 'Thủ Đức',
    address: '28 Nguyễn Văn Hưởng, Thảo Điền, TP. Hồ Chí Minh',
    type: 'HOMESTAY' as const,
    pricePerNight: 1450000,
    depositPercent: 50,
    maxGuests: 4,
    photo: 'photo-1600607687939-ce8a6c25118c',
    codes: ['WIFI', 'AIR_CONDITIONING', 'SWIMMING_POOL', 'BALCONY', 'KITCHEN'],
  },
].map(({ photo, codes, ...data }, index) => ({
  data: {
    ...data,
    name: legacySeedNames[index],
    bedrooms: data.maxGuests > 3 ? 2 : 1,
    beds: data.maxGuests > 2 ? 2 : 1,
    bathrooms: 1,
    description:
      'Một không gian sáng thoáng, ấm áp và riêng tư để bạn tận hưởng nhịp sống Sài Gòn theo cách của mình. Nội thất gỗ tự nhiên, giường ngủ êm ái cùng những tiện nghi cần thiết cho chuyến đi. Gần các quán cà phê, nhà hàng và điểm khám phá địa phương. Toàn bộ chỗ nghỉ dành riêng cho nhóm của bạn. Nhận phòng từ 14:00, trả phòng trước 12:00. Vui lòng giữ yên tĩnh sau 22:00.',
  },
  codes,
  images: [
    photo,
    'photo-1615874959474-d609969a20ed',
    'photo-1600566753086-00f18fb6b3ea',
  ].map((image, sortOrder) => ({
    url: `https://images.unsplash.com/${image}?auto=format&fit=crop&w=1400&q=85`,
    sortOrder,
  })),
}));
