services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - server

  server:
    build:
      context: ./backend
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: "service_healthy"
    command: >
      sh -c "prisma db push && node dist/seed/seed.js && exec node dist/main.js"

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -pstayhub || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 15s
volumes:
  mysql_data:
